Honor/Controllers/Select2Controller.cs
using Honor.Entities.SIM;
using Honor.Helper;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Honor.Controllers
{
    [Authorize]
    public class Select2Controller : Controller
    {
        [HttpPost]
        public string HitungHonor_Dokter(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.HR_GetDokter.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.DokterID.Contains(filter) ||
                            x.NamaDOkter.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.NamaDOkter).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.DokterID,
                        Nama = m.NamaDOkter
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        //#region ===== J A S A

        //[HttpPost]
        //public string Jasa_Jasa_GroupJasa(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_ListGroupJasa.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.GroupJasaName.Contains(filter) ||
        //                    x.KelompokPerawatan.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.GroupJasaName).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.GroupJasaID,
        //                Nama = m.GroupJasaName
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }

        //}

        //[HttpPost]
        //public string Jasa_Jasa_KategoriJasa(int pagesize, int pageindex, string filter, byte? groupjasa)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetKategoriJasa.AsQueryable();
        //            if (groupjasa != null) proses = proses.Where(x => x.GroupJasa == groupjasa);
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.KategoriJasaID.Contains(filter) ||
        //                    x.NamaInternational.Contains(filter) ||
        //                    x.KategoriJasaName.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.GroupJasaName).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.KategoriJasaID,
        //                Nama = m.KategoriJasaName
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }

        //}

        //[HttpPost]
        //public string Jasa_Jasa_Dokter(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_ListVendor.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.Kode_Supplier.Contains(filter) ||
        //                    x.Nama_Supplier.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.Kode_Supplier).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.Kode_Supplier,
        //                Kode = m.Kode_Supplier,
        //                Nama = m.Nama_Supplier
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }
        //}

        //[HttpPost]
        //public string Jasa_Jasa_Akun(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetKomponenAkun.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.Akun_No.Contains(filter) ||
        //                    x.Akun_Name.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.Akun_No).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.Akun_No,
        //                Kode = m.Akun_No,
        //                Nama = m.Akun_Name
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }
        //}

        //[HttpPost]
        //public string Jasa_Jasa_Section(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetLookUpDetailSection.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.SectionName.Contains(filter) ||
        //                    x.ID.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.SectionName).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.ID,
        //                Nama = m.SectionName
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }
        //}

        //[HttpPost]
        //public string Jasa_Jasa_DataLAB(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetLookUpDetailDataLAB.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.ID.Contains(filter) ||
        //                    x.NamaTest.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();

Honor/Views/HitungHonor/Setup.cshtml
@using Honor.Helper 
<div id="modalsetup" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Hitung Honor</h4>
            </div>
            <form autocomplete="off">
                <div class="modal-body">
                    <div class="form-horizontal">
                        <input type="hidden" name="_PROCESS" />
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">No Bukti</label>
                                    <div class="col-md-8">
                                        <input type="text" name="NoBukti" class="form-control all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Tipe Honor</label>
                                    <div class="col-md-8">
                                        <select name="TipeHonor" required class="form-control">
                                            @Html.Raw(HList.Honor_TipeHonor)
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Filter Dokter</label>
                                    <div class="col-md-8">
                                        <select name="FilterDokter" class="form-control">
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Periode</label>
                                    <div class="col-md-8">
                                        <input type="date" name="Periode" required class="form-control" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Keterangan</label>
                                    <div class="col-md-8">
                                        <input type="text" name="Keterangan" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> SAVE</button>
                    <button type="submit" class="btn-delete btn btn-danger"><i class="glyphicon glyphicon-trash"></i> DELETE</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var isetup;
    document.addEventListener("DOMContentLoaded", function (event) {
        isetup = new iSetup({
            modal: 'modalsetup',
            urldetail: '@Url.Action("Detail")',
            urlsave: '@Url.Action("Save")',
            detailsuccess: function (r, proc) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    var t = isetup.form;

                    // detail value
                    t['NoBukti'].value = r.Data.NoBukti;
                    t['TipeHonor'].value = r.Data.TipeHonor;
                    t['FilterDokter'].value = r.Data.FilterDokter;
                    t['Periode'].value = r.Data.Periode;
                    t['Keterangan'].value = r.Data.Keterangan;

                    isetup.init();

                    isetup.modal.modal({backdrop: 'static'});
                } else
                    alert(r.Message);
            },
            saveparam: function () {
                var t = isetup.form;
                return {
                    _process : t['_PROCESS'].value,
                    model: {

                        // param
                        TipeHonor: t['TipeHonor'].value,
                        NoBukti: t['NoBukti'].value,
                        Periode: t['Periode'].value,
                        FilterDokter: t['FilterDokter'].value,
                        Keterangan: t['Keterangan'].value,

                    }
                }
            },
            savesuccess: function (r) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    isetup.modal.modal('hide');
                    itable.refresh();
                } else
                    alert(r.Message);
            },
            setupready: function () {
                var t = isetup.form;
                if (t['_PROCESS'].value === 'DELETE') $(t).find('[type="submit"].btn-danger').focus();
            },
            onopenmodalcreate: function (t) {
                isetup.init();
            }
        });

        $(isetup.form['TipeHonor']).select2();
        $(isetup.form['FilterDokter']).select2({
            ajax: {
                url: "@Url.Action("HitungHonor_Dokter", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return {
                            results: $.map(data.Data, function (value, index) {
                                return {
                                    id: value.Id,
                                    text: value.Nama,
                                }
                            }), pagination: { more: (params.page * 30) < data.TotalCount }
                        };
                    }
                }, cache: true
            },
            allowClear: true,
            placeholder: "Dokter"
        });
    });
</script>

Honor/Views/HitungHonor/_ViewDokter.cshtml
@using Honor.Helper
<div id="modalsetupdetaildokter" class="modal fade" role="dialog" style="z-index:1060;">
    <div class="modal-dialog modal-full">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Hitung Honor</h4>
            </div>
            <form autocomplete="off">
                <div class="modal-body">
                    <div class="form-horizontal">
                        <input type="hidden" name="_PROCESS" />
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Nama Dokter</label>
                                    <div class="col-md-8">
                                        <input type="text" name="NamaDokter" class="form-control all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Total Honor</label>
                                    <div class="col-md-8">
                                        <input type="text" name="TotalHonor" class="form-control all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Total Pajak</label>
                                    <div class="col-md-8">
                                        <input type="text" name="TotalPajak" class="form-control all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Alat Dokter</label>
                                    <div class="col-md-8">
                                        <input type="text" name="AlatDokter" class="form-control all-readonly" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Total Rumkit</label>
                                    <div class="col-md-8">
                                        <input type="text" name="TotalRumkit" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Total RSU</label>
                                    <div class="col-md-8">
                                        <input type="text" name="TotalRSU" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Honor Nett</label>
                                    <div class="col-md-8">
                                        <input type="text" name="HonorNett" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Akumulasi Honor Sebelumnya</label>
                                    <div class="col-md-8">
                                        <input type="text" name="AkumulasiHonorSebelumnya" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Pajak DPP</label>
                                    <div class="col-md-8">
                                        <input type="text" name="PajakDPP" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Pajak Tarif</label>
                                    <div class="col-md-8">
                                        <input type="text" name="PajakTarif" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Pajak Nominal</label>
                                    <div class="col-md-8">
                                        <input type="text" name="PajakNominal" class="form-control text-right all-readonly" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="table-responsive">
                                <table class="table table-xxs table-bordered">
                                    <thead>
                                        <tr>
                                            <td>Pasien</td>
                                            <td>NoReg</td>
                                            <td>Jenis Pasien</td>
                                            <td>TglTindakan</td>
                                            <td>JasaName</td>
                                            <td>Kelas</td>
                                            <td>Keterangan</td>
                                            <td>Qty</td>
                                            <td>Tarif</td>
                                            <td>Diskon</td>
                                            <td>Potongan</td>
                                            <td>KetPotongan</td>
                                            <td>NoInvoice</td>
                                            <td>Validasi</td>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var isetup_dokter;
    document.addEventListener("DOMContentLoaded", function (event) {
        isetup_dokter = new iSetup({
            modal: 'modalsetupdetaildokter',
            urldetail: '@Url.Action("Detail_dokter")',
            detailsuccess: function (r, proc) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    var t = isetup_dokter.form;

                    // detail value
                    t['NamaDokter'].value = r.Data.NamaDokter;
                    t['TotalHonor'].value = getcurrencyfromfloat(r.Data.TotalHonor) || '0';
                    t['TotalPajak'].value = getcurrencyfromfloat(r.Data.TotalPajak) || '0';
                    t['AlatDokter'].value = getcurrencyfromfloat(r.Data.AlatDokter) || '0';
                    t['TotalRumkit'].value = getcurrencyfromfloat(r.Data.TotalRumkit) || '0';
                    t['TotalRSU'].value = getcurrencyfromfloat(r.Data.TotalRSU) || '0';
                    t['HonorNett'].value = getcurrencyfromfloat(r.Data.HonorNett) || '0';
                    t['AkumulasiHonorSebelumnya'].value = getcurrencyfromfloat(r.Data.AkumulasiHonorSebelumnya) || '0';
                    t['PajakDPP'].value = getcurrencyfromfloat(r.Data.PajakDPP) || '0';
                    t['PajakTarif'].value = getcurrencyfromfloat(r.Data.PajakTarif) || '0';
                    t['PajakNominal'].value = getcurrencyfromfloat(r.Data.PajakNominal) || '0';

                    let detail = '';
                    r.Detail.forEach(x => {
                        detail += `<tr>`;
                        detail += `<td>${x.Pasien}</td>`;
                        detail += `<td>${x.NoReg}</td>`;
                        detail += `<td>${x.JnPasien || '-'}</td>`;
                        detail += `<td>${x.TglTindakan}</td>`;
                        detail += `<td>${x.JasaName}</td>`;
                        detail += `<td>${x.Kelas}</td>`;
                        detail += `<td>${x.Keterangan || '-'}</td>`;
                        detail += `<td>${x.Qty}</td>`;
                        detail += `<td>${getcurrencyfromfloat(x.Tarif) || '0'}</td>`;
                        detail += `<td>${x.Diskon}</td>`;
                        detail += `<td>${getcurrencyfromfloat(x.Potongan) || '0'}</td>`;
                        detail += `<td>${x.KetPotongan}</td>`;
                        detail += `<td>${x.NoInvoice}</td>`;
                        detail += `<td class="text-center"><input type="checkbox" disabled ${x.Validasi && 'checked'}/></td>`;
                        detail += `</tr>`;
                    });

                    $(isetup_dokter.form).find('table tbody').html(detail);
                    isetup_dokter.init();

                    isetup_dokter.modal.modal({backdrop: 'static'});
                    $('.modal-backdrop:last').css('z-index', $('#modalsetupdetaildokter').css('z-index') - 1);
                } else
                    alert(r.Message);
            }
        });

        $('#modalsetupdetaildokter').on('hidden.bs.modal', function () {
            $('body').addClass('modal-open');
        });

        $(isetup_dokter.form['TipeHonor']).select2();
        $(isetup_dokter.form['FilterDokter']).select2({
            ajax: {
                url: "@Url.Action("HitungHonor_Dokter", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return {
                            results: $.map(data.Data, function (value, index) {
                                return {
                                    id: value.Id,
                                    text: value.Nama,
                                }
                            }), pagination: { more: (params.page * 30) < data.TotalCount }
                        };
                    }
                }, cache: true
            },
            allowClear: true,
            placeholder: "Dokter"
        });
    });
</script>